[network]
host = "127.0.0.1"
port = 6969
public_host = "http://127.0.0.1:6969"
allow_private_network = true

[db]
host = "127.0.0.1"
port = 6961

[peers]
bootstrap_peers = ["http://127.0.0.1:4969"]

[explorer]
enable = true

[api]
enable = true
rate_limiter_requests = 100000
rate_limiter_duration = 10000 # milliseconds

[storage]
max_profile_size = 30 # Megabytes
limit = 2 # Gigabytes

[garbage_collector]
frequency = 240 # seconds
enable = true
profile_expiry = 30 # days

[dht]
enable_updater = true
updater_frequency = 5 # seconds

[pins]
allow_publish = true
enable_downloader = true
enable_updater = true
updater_frequency = 5 # seconds
downloader_frequency = 5 # seconds

[update]
enable = true
id = "SHOGbf74d28baf7a281a81e412420090b91d"